Repository andela/knights-bn-backend, pull requests merged in 2020-03, with the labels that each got.

#26 #170947656 Send email verification link
  .gitignore
  env.example
  package.json
  src/controllers/users.js
  src/index.js
  src/middlewares/newUser.js
  src/middlewares/validateOneWay.js
  src/routes/users.js
  src/tests/mockData.js
  src/tests/request.test.js
  src/tests/user.test.js
  src/tests/userLogin.test.js
  uploads/2020-02-25T13:50:55.296Ztest.png
  uploads/2020-02-25T13:53:31.485Ztest.png
  uploads/2020-02-25T13:55:00.670Ztest.png
  uploads/2020-02-25T14:27:57.776Ztest.png
  uploads/2020-02-25T14:29:37.306Ztest.png
  uploads/2020-02-25T14:33:57.966Ztest.png
  uploads/2020-02-25T14:36:29.492Ztest.png
  uploads/2020-02-25T16:22:44.293Ztest.png
  uploads/2020-02-25T16:33:04.317Ztest.png
  uploads/2020-02-25T16:35:34.355Ztest.png
  uploads/2020-02-25T16:43:14.781Ztest.png
  uploads/2020-02-25T16:44:24.270Ztest.png
  uploads/2020-02-26T08:33:48.718Ztest.png
  uploads/2020-02-26T08:35:24.316Ztest.png
  uploads/2020-02-26T08:36:46.129Ztest.png
  uploads/2020-02-26T08:37:20.091Ztest.png
  uploads/2020-02-26T08:38:04.702Ztest.png
  uploads/2020-02-27T14:43:22.159Ztest.png
  uploads/2020-02-27T14:44:43.697Ztest.png
  uploads/2020-02-27T14:46:22.936Ztest.png
  uploads/2020-02-27T14:47:47.227Ztest.png
  uploads/2020-02-27T20:30:58.090Ztest.png
  uploads/2020-02-27T20:31:18.140Ztest.png
  uploads/2020-02-28T04:11:45.431Ztest.png
  uploads/2020-02-28T04:13:32.033Ztest.png
  uploads/2020-02-28T04:28:33.557Ztest.png
  uploads/2020-02-28T04:29:15.956Ztest.png
  uploads/2020-02-28T04:31:44.038Ztest.png
  uploads/2020-02-28T04:33:20.406Ztest.png
  uploads/2020-02-28T04:34:26.701Ztest.png
  uploads/2020-02-28T04:37:22.028Ztest.png
  uploads/2020-02-28T04:39:04.687Ztest.png
  uploads/2020-02-28T04:41:50.221Ztest.png
  uploads/2020-02-28T04:43:10.914Ztest.png
  uploads/2020-02-28T04:49:16.340Ztest.png
  uploads/2020-02-28T04:49:41.938Ztest.png
  uploads/2020-02-28T06:43:52.921Ztest.png
  uploads/2020-02-28T06:44:19.527Ztest.png
  uploads/2020-02-28T06:44:53.944Ztest.png
Labels: Good for review

#40 #170947670 Reject a trip request
  .gitignore
  README.md
  package.json
  src/controllers/request.js
  src/db/seeders/20200218073358-Request.js
  src/middlewares/verifyToken.js
  src/routes/trips.js
  src/tests/mainTest.test.js
  src/tests/mockData.js
  src/tests/rejectRequest.test.js
  src/tests/socialLogin.test.js
  src/utils/isObjectEmpty.js
Labels: Good for review

#38 #170947666 make one travel request has multiple stops
  README.md
  package-lock.json
  package.json
  src/controllers/request.js
  src/controllers/userProfile.js
  src/db/models/request.js
  src/db/seeders/20200217084540-user.js
  src/helpers/validateDate.js
  src/middlewares/validateDate.js
  src/routes/trips.js
  src/tests/mainTest.test.js
  src/tests/mockData.js
  src/tests/multicityRequest.test.js
Labels: Good for review

#44 #170947676 Add Search Functionality
  .gitignore
  README.md
  src/controllers/request.js
  src/controllers/searchRequest.js
  src/helpers/filterRequest.js
  src/routes/trips.js
  src/tests/request.test.js
Labels: Good for review

#43 #170947667 notification for new request made
  package-lock.json
  package.json
  src/app.js
  src/controllers/request.js
  src/controllers/userProfile.js
  src/controllers/users.js
  src/db/migrations/20200228100755-create-notification.js
  src/db/migrations/20200229162834-update-notification-status.js
  src/db/models/notification.js
  src/db/seeders/20200217084540-user.js
  src/helpers/notificationSender.js
  src/helpers/userValidation.js
  src/index.js
  src/middlewares/checkAuth.js
  src/middlewares/newUser.js
  src/middlewares/validateReturnTrip.js
  src/middlewares/verifyToken.js
  src/mockData/twoWayTrip.js
  src/routes/trips.js
  src/tests/app.test.js
  src/tests/index.test.js
  src/tests/mainTest.test.js
  src/tests/mockData.js
  src/tests/multicityRequest.test.js
  src/tests/rejectRequest.test.js
  src/tests/request.test.js
  src/tests/twoWayTrip.test.js
  src/tests/user.test.js
Labels: Good for review

#41 #170947673 allow requester to be remembered nextime
  .eslintrc.json
  README.md
  package-lock.json
  package.json
  src/app.js
  src/controllers/userProfile.js
  src/routes/users.js
  src/tests/getUserAnEditProfileInfo.test.js
  src/tests/mainTest.test.js
  src/tests/mockData.js
  src/tests/multicityRequest.test.js
  src/tests/rememberMe.test.js
Labels: Good for review

#42 #170947664 - Make One-way Trip Request
  .gitignore
  package.json
  src/app.js
  src/controllers/request.js
  src/docs/swaggerDefinition.js
  src/helpers/oneWayTrip.js
  src/middlewares/validateOneWay.js
  src/routes/trips.js
  src/tests/mockData.js
  src/tests/request.test.js
Labels: Good for review

#47 #170947672 comment on my request
  src/controllers/comment.controller.js
  src/controllers/request.js
  src/db/migrations/20200304100142-create-comment.js
  src/db/models/comment.js
  src/db/models/request.js
  src/helpers/commentValidation.js
  src/helpers/userQueries.js
  src/middlewares/commenter.js
  src/middlewares/newComment.js
  src/mockData/twoWayTrip.js
  src/routes/trips.js
  src/tests/comment.test.js
  src/tests/mainTest.test.js
  src/tests/mockData.js
Labels: Good for review

#45 #170947677 mark all notifications as read
  README.md
  src/controllers/notifications.js
  src/controllers/request.js
  src/controllers/users.js
  src/db/migrations/20200304084321-edit-notification.js
  src/db/models/notification.js
  src/db/seeders/20200217084540-user.js
  src/db/seeders/20200304121949-notification.js
  src/helpers/getNotifications.js
  src/routes/trips.js
  src/tests/mockData.js
  src/tests/notifications.test.js
Labels: Good for review

#57 #171685721 enable maintainability checks
  .codeclimate.yml
Labels: Good for review, priority

#53 #170947675 user can delete their comment
  .eslintrc.js
  .eslintrc.json
  package-lock.json
  package.json
  src/controllers/comment.controller.js
  src/controllers/notifications.js
  src/controllers/request.js
  src/controllers/searchRequest.js
  src/controllers/userProfile.js
  src/controllers/users.js
  src/db/migrations/20200304100142-create-comment.js
  src/helpers.js/userValidation.js
  src/helpers/commentQueries.js
  src/helpers/filterRequest.js
  src/helpers/getNotifications.js
  src/helpers/imageHelpers.js
  src/helpers/notificationSender.js
  src/helpers/oneWayTrip.js
  src/helpers/returnProfileInformation.js
  src/helpers/tokenGenerator.js
  src/helpers/userQueries.js
  src/helpers/userValidation.js
  src/middlewares/checkAuth.js
  src/middlewares/commenter.js
  src/middlewares/deleteCommentChecker.js
  src/middlewares/imageUpload.js
  src/middlewares/newUser.js
  src/middlewares/userLoginValidation.js
  src/middlewares/validateDate.js
  src/middlewares/validateOneWay.js
  src/middlewares/validateReturnTrip.js
  src/mockData/twoWayTrip.js
  src/routes/trips.js
  src/routes/users.js
  src/tests/comment.test.js
  src/tests/mockData.js
  src/tests/request.test.js
Labels: Good for review

#49 #170947678 User can edit an open request
  .eslintrc.js
  .eslintrc.json
  README.md
  package-lock.json
  package.json
  src/app.js
  src/controllers/request.js
  src/middlewares/splitUrl.js
  src/middlewares/validateReturnTrip.js
  src/mockData/requestMock.js
  src/mockData/twoWayTrip.js
  src/routes/trips.js
  src/tests/editRequest.test.js
  src/tests/mainTest.test.js
  src/tests/mockData.js
  src/tests/rejectRequest.test.js
  src/tests/request.test.js
  src/tests/twoWayTrip.test.js
  src/utils/updateRequest.js
  src/utils/validationSchemas.js
Labels: Good for review

#54 #170947681 Allow travel admin to create accommodation facilities
  .eslintrc.json
  src/app.js
  src/controllers/accommodation.js
  src/db/migrations/20200205203623-create-client.js
  src/db/migrations/20200205203644-create-reservation.js
  src/db/migrations/20200208090739-create-user.js
  src/db/migrations/20200213181730-create-user.js
  src/db/migrations/20200220144524-create-request.js
  src/db/migrations/20200222174400-user-profile-information.js
  src/db/migrations/20200224061653-multi-stop-column.js
  src/db/migrations/20200225204153-two-way-trip-update-users.js
  src/db/migrations/20200225205113-two-way-trip-update-requests.js
  src/db/migrations/20200228061144-update-users-role.js
  src/db/migrations/20200228061154-update-users-gender.js
  src/db/migrations/20200228061201-update-users-method.js
  src/db/migrations/20200228061309-update-requests-status.js
  src/db/migrations/20200228061335-update-requests-type.js
  src/db/migrations/20200228100755-create-notification.js
  src/db/migrations/20200229162834-update-notification-status.js
  src/db/migrations/20200304084321-edit-notification.js
  src/db/migrations/20200304100142-create-comment.js
  src/db/migrations/20200305205253-create-accommodation.js
  src/db/models/accommodation.js
  src/db/seeders/20200205204755-client.js
  src/db/seeders/20200205204808-reservation.js
  src/db/seeders/20200217084540-user.js
  src/db/seeders/20200218073358-Request.js
  src/db/seeders/20200225213741-two_way_trip.js
  src/db/seeders/20200304121949-notification.js
  src/db/seeders/20200306190227-accommodation.js
  src/middlewares/isTravelAdmin.js
  src/middlewares/newComment.js
  src/middlewares/validateDate.js
  src/routes/accommodation.js
  src/routes/trips.js
  src/tests/accommodation/accommodationMockData.js
  src/tests/accommodation/createAccommodationFacility.test.js
  src/tests/accommodation/imageUploadAccommodation.test.js
  src/tests/mainTest.test.js
  src/tests/mockData.js
  src/tests/multicityRequest.test.js
  src/tests/notifications.test.js
  src/utils/isObjectEmpty.js
Labels: Good for review

#60 #170947685 allow suppliers to add their accommodation
  .eslintrc.js
  src/controllers/accommodation.js
  src/db/migrations/20200228061144-update-users-role.js
  src/db/seeders/20200217084540-user.js
  src/middlewares/isTravelAdmin.js
  src/tests/accommodation/accommodationMockData.js
  src/tests/accommodation/createAccommodationFacility.test.js
  src/tests/twoWayTrip.test.js
  src/tests/user.test.js
Labels: Good for review

#59 #170947693 users should be able to chat
  .eslintrc.js
  src/app.js
  src/controllers/chat.js
  src/controllers/users.js
  src/db/migrations/20200309131726-create-chats.js
  src/db/models/chats.js
  src/helpers/decodeToken.js
  src/helpers/eventConnect.js
  src/helpers/ioServerHelper.js
  src/middlewares/checkAuth.js
  src/routes/chat.js
  src/tests/mainTest.test.js
  src/tests/request.test.js
Labels: Good for review

#56 #170947674 Send notification for the approved request
  .babelrc
  .eslintrc.js
  .eslintrc.json
  README.md
  src/app.js
  src/controllers/request.js
  src/controllers/users.js
  src/db/models/notification.js
  src/db/seeders/20200218073358-Request.js
  src/db/seeders/20200225213741-two_way_trip.js
  src/helpers/Request.js
  src/helpers/addNotification.js
  src/helpers/compareDates.js
  src/helpers/errorHandler.js
  src/helpers/generateToken.js
  src/helpers/getTodayDate.js
  src/helpers/ioServerHelper.js
  src/helpers/isObjectEmpty.js
  src/helpers/randomPswd.js
  src/helpers/sendEmail.js
  src/helpers/userQueries.js
  src/helpers/validationSchemas.js
  src/middlewares/validateParams.js
  src/middlewares/validateReturnTrip.js
  src/mockData/twoWayMock.js
  src/routes/trips.js
  src/tests/approveRequest.test.js
  src/tests/editRequest.test.js
  src/tests/mainTest.test.js
  src/tests/rejectRequest.test.js
  src/tests/viewSpecificRequest.test.js
  src/utils/isObjectEmpty.js
  src/utils/updateRequest.js
Labels: Good for review

#65 170947680 - Send Notification for Posted Comments
  src/controllers/comment.controller.js
  src/controllers/request.js
  src/helpers/TripHelper.js
  src/routes/trips.js
  src/routes/users.js
Labels: Good for TTL Review

#62 #170947690 rate accomodations
  .env.example
  package.json
  src/config/passport.js
  src/controllers/rate.accommodation.js
  src/db/config/config.js
  src/db/migrations/20200305205253-create-accommodation.js
  src/db/migrations/20200311154810-create-rate.js
  src/db/models/accommodation.js
  src/db/models/comment.js
  src/db/models/notification.js
  src/db/models/rate.js
  src/db/models/user.js
  src/db/seeders/20200306190227-accommodation.js
  src/docs/swaggerDefinition.js
  src/helpers/commentQueries.js
  src/helpers/compareDates.js
  src/helpers/isObjectEmpty.js
  src/helpers/queries.js
  src/helpers/rateQueries.js
  src/helpers/validationSchemas.js
  src/middlewares/deleteCommentChecker.js
  src/middlewares/validateDate.js
  src/middlewares/validateParams.js
  src/middlewares/validateParamsRate.js
  src/middlewares/validateRate.js
  src/middlewares/validateReturnTrip.js
  src/mockData/facebookFakeUser.js
  src/mockData/googleFakeUser.js
  src/mockData/requestMock.js
  src/mockData/twoWayMock.js
  src/mockData/twoWayTrip.js
  src/modules/email.js
  src/routes/accommodation.js
  src/routes/chat.js
  src/routes/trips.js
  src/routes/users.js
  src/tests/accommodation/accommodationMockData.js
  src/tests/accommodation/createAccommodationFacility.test.js
  src/tests/accommodation/rate.accommodation.test.js
  src/tests/getUserAnEditProfileInfo.test.js
  src/tests/mainTest.test.js
  src/tests/request.test.js
  src/tests/twoWayTrip.test.js
  src/tests/viewSpecificRequest.test.js
  src/translator.js
Labels: Good for TTL Review

#64 170947686-ft(accommodation): book an accommodation
  README.md
  src/app.js
  src/controllers/accommodation.js
  src/controllers/booking.js
  src/db/migrations/20200311175508-create-bookings.js
  src/db/models/bookings.js
  src/db/seeders/20200306190227-accommodation.js
  src/helpers/filterRequest.js
  src/helpers/queries.js
  src/middlewares/validateBookings.js
  src/middlewares/validateDate.js
  src/routes/accommodation.js
  src/routes/booking.js
  src/routes/chat.js
  src/tests/accommodation/accommodationMockData.js
  src/tests/accommodation/rate.accommodation.test.js
  src/tests/booking.test.js
  src/tests/mainTest.test.js
  src/tests/mockData.js
Labels: Good for TTL Review

#68 #170947679 Send notification to the manager when request is edited
  .env.example
  README.md
  package-lock.json
  package.json
  public/client/editEvent.js
  public/client/editRequest.html
  public/client/main.js
  public/client/notification.js
  src/app.js
  src/controllers/accommodation.js
  src/controllers/request.js
  src/controllers/userProfile.js
  src/events/editEvent.js
  src/helpers/Request.js
  src/helpers/queries.js
  src/helpers/returnNotification.js
  src/helpers/returnProfileInformation.js
  src/helpers/validateDate.js
  src/middlewares/findAccommodation.js
  src/middlewares/imageUpload.js
  src/middlewares/splitUrl.js
  src/middlewares/validateDate.js
  src/routes/accommodation.js
  src/routes/trips.js
  src/routes/users.js
  src/tests/accommodation/accommodationMockData.js
  src/tests/accommodation/createAccommodationFacility.test.js
  src/tests/accommodation/imageUploadAccommodation.test.js
  src/tests/approveRequest.test.js
  src/tests/booking.test.js
  src/tests/comment.test.js
  src/tests/editRequest.test.js
  src/tests/getUserAnEditProfileInfo.test.js
  src/tests/mainTest.test.js
  src/tests/mockEditNotification/credentials.js
  src/tests/mockEditNotification/emailtesting.js
  src/tests/multicityRequest.test.js
  src/tests/rejectRequest.test.js
  src/tests/rememberMe.test.js
  src/tests/request.test.js
  src/tests/twoWayTrip.test.js
  src/tests/userLogin.test.js
Labels: Good for TTL Review

#69 #170947691 Add stats for trips made
  .eslintrc.js
  README.md
  src/controllers/request.js
  src/helpers/Request.js
  src/helpers/errorHandler.js
  src/helpers/handleSuccess.js
  src/middlewares/validateStatsDate.js
  src/routes/trips.js
  src/tests/getStats.test.js
  src/tests/mainTest.test.js
Labels: Good for TTL Review

#71 170947669- user role settings
  README.md
  src/controllers/booking.js
  src/controllers/comment.controller.js
  src/controllers/users.js
  src/db/migrations/20200228061144-update-users-role.js
  src/db/seeders/20200217084540-user.js
  src/docs/swaggerDefinition.js
  src/helpers/currentEnv.js
  src/helpers/userQueries.js
  src/middlewares/validateRole.js
  src/routes/users.js
  src/tests/getStats.test.js
  src/tests/mainTest.test.js
  src/tests/mockData.js
  src/tests/userRoles.test.js
Labels: Good for TTL Review

#67 #170947688 Make a comment on accommodation
  README.md
  src/app.js
  src/controllers/accommodation.js
  src/controllers/request.js
  src/db/migrations/20200304100142-create-comment.js
  src/db/models/accommodation.js
  src/db/models/comment.js
  src/helpers/queries.js
  src/helpers/returnNotification.js
  src/helpers/returnProfileInformation.js
  src/middlewares/findAccommodation.js
  src/middlewares/validateDate.js
  src/routes/accommodation.js
  src/tests/accommodation/accommodationFeedback.test.js
  src/tests/accommodation/createAccommodationFacility.test.js
  src/tests/accommodation/imageUploadAccommodation.test.js
  src/tests/booking.test.js
  src/tests/mainTest.test.js
  src/tests/notificationFormart.test.js
  src/tests/rememberMe.test.js
Labels: Good for TTL Review

#70 #171815577 improve code maintainability
  public/client/editEvent.js
  src/controllers/booking.js
  src/controllers/notifications.js
  src/controllers/request.js
  src/controllers/searchRequest.js
  src/controllers/users.js
  src/helpers/errorHandler.js
  src/helpers/sendEmail.js
  src/middlewares/commenter.js
  src/middlewares/newUser.js
  src/middlewares/splitUrl.js
  src/middlewares/validateDate.js
  src/middlewares/validateReturnTrip.js
  src/routes/accommodation.js
  src/tests/accommodation/accommodationFeedback.test.js
  src/tests/accommodation/accommodationMockData.js
  src/tests/accommodation/createAccommodationFacility.test.js
  src/tests/accommodation/imageUploadAccommodation.test.js
  src/tests/accommodation/mostTravelled.test.js
  src/tests/accommodation/rate.accommodation.test.js
  src/tests/mainTest.test.js
  src/tests/notifications.test.js
  src/tests/request.test.js
  src/tests/user.test.js
Labels: Good for TTL Review

#72 #170947687 User should be able to like/unlike accommodation
  README.md
  package-lock.json
  src/controllers/accommodation.js
  src/controllers/request.js
  src/db/migrations/20200305205253-create-accommodation.js
  src/db/models/accommodation.js
  src/db/models/user.js
  src/helpers/likeAndDislike.js
  src/middlewares/dislikeUser.js
  src/middlewares/findAccommodation.js
  src/middlewares/likeUser.js
  src/routes/accommodation.js
  src/tests/accommodation/accommodationMockData.js
  src/tests/accommodation/createAccommodationFacility.test.js
  src/tests/accommodation/likeUnlike.test.js
  src/tests/getUserAnEditProfileInfo.test.js
  src/tests/mainTest.test.js
  src/tests/userRoles.test.js
Labels: Good for TTL Review

#77 #171911664: Improve test coverage on app.js
  package-lock.json
  package.json
  src/app.js
  src/controllers/request.js
  src/helpers/eventConnect.js
  src/tests/app.test.js
  src/tests/comment.test.js
  src/tests/mainTest.test.js
  src/tests/request.test.js
Labels: Good for TTL Review

#78 #171947441 improve test coverage on returnTrip.js
  .eslintrc.js
  src/controllers/accommodation.js
  src/controllers/booking.js
  src/controllers/request.js
  src/helpers/Request.js
  src/helpers/getConflictingRequest.js
  src/helpers/getUrlAddress.js
  src/helpers/returnNotification.js
  src/helpers/sendEmail.js
  src/middlewares/validateReturnTrip.js
  src/routes/accommodation.js
  src/routes/users.js
  src/tests/mainTest.test.js
  src/tests/twoWayTrip.test.js
Labels: Good for TTL Review
